plugins { id 'net.fabricmc.fabric-loom' }
base { archivesName = 'rubidium-audit-dev-only-26.1' }
dependencies {
    implementation project(':minecraft-26.1')
    minecraft 'com.mojang:minecraft:26.1'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.145.1+26.1'
}
java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }
tasks.withType(JavaCompile).configureEach { options.release = 25 }
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version) }
}
